### ISSUE TITLE
Distinguish Extreme from Savage content with colors

### ISSUE THREAD

**Issue by zbee** [FFXIVPocketGuide/FFXIVPocketGuide#187]
Currently, it is difficult to differentiate at a glance between Extreme and Savage content as shown in the image below, as both use the same color for the text (despite having separate CSS classes).

I would suggest that Savage content receive a different color than Extreme. I don't immediately see any color suggestions from SE. However I do have two ideas for it:

- Keep Hard/Extreme colors the same, and change Savage to Pink or Purple.
- Change Hard to Green, Extreme to Blue, and Savage to Pink - similar to item tiers.

![image](https://user-images.githubusercontent.com/1582821/124947118-cec0db00-dfcc-11eb-97f6-9fb8dc72d2fa.png)

**Comment by JoshBeveridge** [comment]
Hey @zbee! Thanks for submitting this issue. You'll hopefully see a change once our latest PR is merged in. :)
